-- Migration: 043_repurpose_user_profiles_for_b2b.sql
-- Description: Repurposes the user_profiles table from B2C travel recommendation
--              to B2B competitive intelligence.
--
-- Adds three new columns for the Compset Intelligence Agent output.
-- Drops three inapplicable B2C columns that were auto-generated in commit 172cbc59
-- (lifestyle_embedding, travel_persona_tags, is_cold_start) and are unused
-- in production.
--
-- SAFE TO RUN: Uses IF EXISTS / IF NOT EXISTS guards throughout.

-- ============================================================
-- STEP 1: Add new B2B columns
-- ============================================================

ALTER TABLE public.user_profiles
    ADD COLUMN IF NOT EXISTS compset_weights JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS competitor_blind_spots TEXT[] DEFAULT '{}'::text[],
    ADD COLUMN IF NOT EXISTS last_compset_analysis TIMESTAMP WITH TIME ZONE;

COMMENT ON COLUMN public.user_profiles.compset_weights IS
    'Output of CompsetIntelligenceAgent: JSON map of competitor names to attention '
    'weights (0.0-1.0) inferred from the revenue manager''s dashboard interactions. '
    'Example: {"Hilton Garden Inn": 0.72, "Willmont Hotel": 0.18}';

COMMENT ON COLUMN public.user_profiles.competitor_blind_spots IS
    'List of competitor names that appear in the compset but receive little or no '
    'dashboard interaction — potential strategic blind spots surfaced by the AI agent.';

COMMENT ON COLUMN public.user_profiles.last_compset_analysis IS
    'Timestamp of the last CompsetIntelligenceAgent run for this user. '
    'Used to schedule incremental re-analysis when new signals accumulate.';

-- Index for finding users whose compset analysis is stale or missing
CREATE INDEX IF NOT EXISTS idx_user_profiles_last_compset_analysis
    ON public.user_profiles (last_compset_analysis NULLS FIRST);

-- ============================================================
-- STEP 2: Drop inapplicable B2C columns
--
-- These columns were generated by a previous AI session (commit 172cbc59)
-- implementing a B2C traveler recommendation engine.  They are semantically
-- incorrect for a B2B hotelier platform and are confirmed unused in production.
-- ============================================================

ALTER TABLE public.user_profiles
    DROP COLUMN IF EXISTS lifestyle_embedding,
    DROP COLUMN IF EXISTS travel_persona_tags,
    DROP COLUMN IF EXISTS is_cold_start;
