import os
from jinja2 import Environment, FileSystemLoader, select_autoescape

# Get the path to the templates directory
TEMPLATES_DIR = os.path.dirname(os.path.abspath(__file__))
jinja_env = Environment(
    loader=FileSystemLoader(TEMPLATES_DIR),
    autoescape=select_autoescape(['html', 'xml'])
)

def build_deep_ocean_briefing_html(
    report_type_clean: str,
    target_name: str,
    timeframe: str,
    date_str: str,
    middle_cards_html: str,
    narrative: str,
    is_archived: bool = False
) -> str:
    """Generates the main HTML for the 'Deep Ocean' Agentic Briefing PDF using Jinja2."""
    template = jinja_env.get_template("deep_ocean_briefing.html")
    
    narrative_title = "Archived Strategic Narrative" if is_archived else "Agentic AI Strategic Synthesis"
    footer_text = "Intelligence archived by Agentic Tripzy Hub" if is_archived else "Intelligence generated by Agentic Tripzy Hub"
    
    return template.render(
        report_type_clean=report_type_clean,
        target_name=target_name,
        timeframe=timeframe,
        date_str=date_str,
        middle_cards_html=middle_cards_html,
        narrative_title=narrative_title,
        narrative=narrative,
        footer_text=footer_text
    )

def build_admin_report_html(
    title: str,
    date_str: str,
    hotel_count: int,
    period_months: str,
    ai_insights_html: str,
    hotels_html: str
) -> str:
    """Generates the main HTML for the multi-hotel Comparative Admin Report using Jinja2."""
    template = jinja_env.get_template("admin_report.html")
    return template.render(
        title=title,
        date_str=date_str,
        hotel_count=hotel_count,
        period_months=period_months,
        ai_insights_html=ai_insights_html,
        hotels_html=hotels_html
    )
