def build_deep_ocean_briefing_html(
    report_type_clean: str,
    target_name: str,
    timeframe: str,
    date_str: str,
    middle_cards_html: str,
    narrative: str,
    is_archived: bool = False
) -> str:
    """Generates the main HTML for the 'Deep Ocean' Agentic Briefing PDF."""
    
    narrative_title = "Archived Strategic Narrative" if is_archived else "Agentic AI Strategic Synthesis"
    footer_text = "Intelligence archived by Agentic Tripzy Hub" if is_archived else "Intelligence generated by Agentic Tripzy Hub"
    
    return f"""
    <html>
    <head>
        <style>
            @page {{ size: A4; margin: 0; }}
            body {{ 
                font-family: 'Helvetica', sans-serif; 
                background-color: #0a192f; 
                color: #e6f1ff; 
                margin: 0; 
                padding: 40px;
            }}
            .report-wrapper {{ width: 100%; }}
            .header-table {{ width: 100%; border-bottom: 2px solid #d4af37; padding-bottom: 20px; margin-bottom: 40px; }}
            h1 {{ color: #d4af37; margin: 0; font-size: 28px; }}
            .cadence {{ color: #8892b0; font-size: 14px; text-transform: uppercase; }}
            .grid-table {{ width: 100%; border-spacing: 20px 0; }}
            .card {{ 
                background-color: #112240; 
                border: 1px solid #d4af37; 
                border-radius: 12px; 
                padding: 20px; 
                margin-bottom: 20px;
                vertical-align: top;
            }}
            h2 {{ color: #d4af37; font-size: 18px; margin-top: 0; border-left: 3px solid #d4af37; padding-left: 10px; }}
            .metric-table {{ width: 100%; }}
            .metric-val {{ font-weight: bold; color: #fff; font-size: 20px; }}
            .metric-label {{ color: #8892b0; font-size: 12px; }}
            .narrative {{ line-height: 1.6; font-size: 14px; color: #ccd6f6; white-space: pre-line; }}
            .footer {{ 
                margin-top: 50px; 
                text-align: center; 
                color: #8892b0; 
                font-size: 12px; 
                border-top: 1px solid #233554;
                padding-top: 20px;
            }}
        </style>
    </head>
    <body>
        <div class="report-wrapper">
            <table class="header-table">
                <tr>
                    <td>
                        <h1>{report_type_clean}</h1>
                        <div class="cadence">{target_name} | {timeframe}</div>
                    </td>
                    <td style="text-align: right; vertical-align: bottom;">
                        <div class="cadence">{date_str}</div>
                    </td>
                </tr>
            </table>

            {middle_cards_html}

            <div class="card" style="background-color: #112240;">
                <h2 style="color: #d4af37;">{narrative_title}</h2>
                <div class="narrative">{narrative}</div>
            </div>

            <div class="footer">
                {footer_text} | Specialized Multi-Lens Engine
            </div>
        </div>
    </body>
    </html>
    """

def build_admin_report_html(
    title: str,
    date_str: str,
    hotel_count: int,
    period_months: str,
    ai_insights_html: str,
    hotels_html: str
) -> str:
    """Generates the main HTML for the multi-hotel Comparative Admin Report."""
    return f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Helvetica', sans-serif; color: #333; padding: 40px; }}
            h1 {{ color: #047857; border-bottom: 2px solid #047857; padding-bottom: 10px; }}
            h2 {{ color: #333; margin-top: 30px; }}
            .meta {{ color: #666; font-size: 0.9em; margin-bottom: 30px; }}
            .insight {{ background: #ecfdf5; padding: 15px; border-left: 4px solid #047857; margin-bottom: 10px; }}
            .hotel-card {{ border: 1px solid #ddd; padding: 20px; margin-bottom: 20px; page-break-inside: avoid; }}
            .metric {{ font-size: 1.2em; font-weight: bold; }}
            .label {{ font-size: 0.8em; color: #666; text-transform: uppercase; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #eee; }}
        </style>
    </head>
    <body>
        <h1>{title}</h1>
        <div class="meta">
            Generated on: {date_str}<br/>
            Includes: {hotel_count} hotels | Period: {period_months} months
        </div>

        <h2>🤖 AI Executive Summary</h2>
        {ai_insights_html}

        <h2>🏨 Hotel Analysis</h2>
        {hotels_html}
        
        <div style="margin-top: 50px; text-align: center; color: #999; font-size: 0.8em;">
            Generated by Tripzy.travel Intelligence Hub
        </div>
    </body>
    </html>
    """
